# Generated by Django 4.1.3 on 2023-03-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='name')),
                ('PrivateKey', models.CharField(max_length=255, verbose_name='PrivateKey')),
                ('PublicKey', models.CharField(max_length=255, verbose_name='PublicKey')),
                ('Address', models.CharField(max_length=255, verbose_name='Address')),
                ('DNS', models.CharField(max_length=255, verbose_name='DNS')),
                ('MTU', models.CharField(max_length=255, verbose_name='MTU')),
                ('AllowedIPs', models.CharField(max_length=255, verbose_name='AllowedIPs')),
                ('Endpoint', models.CharField(max_length=255, verbose_name='Endpoint')),
                ('PersistentKeepalive', models.CharField(max_length=255, verbose_name='PersistentKeepalive')),
            ],
        ),
    ]
