# Generated by Django 4.2.4 on 2023-09-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Host', models.CharField(max_length=40, verbose_name='host')),
                ('Username', models.CharField(max_length=255, verbose_name='username')),
                ('Password', models.CharField(max_length=255, verbose_name='password')),
                ('Endpoint', models.CharField(max_length=40, verbose_name='endpoint')),
                ('Network', models.CharField(max_length=40, verbose_name='network')),
                ('Interface', models.CharField(max_length=15, verbose_name='interface')),
                ('MTU', models.CharField(max_length=6, verbose_name='mtu')),
                ('DNS', models.CharField(max_length=40, verbose_name='dns')),
            ],
        ),
    ]
